### PR TITLE
Fix typo in computeds/format.js

### PR DESCRIPTION
**Pull request by Alinaki**
ouputFormat to outputFormat

### CODE REVIEW

**Comment by stefanpenner** [comment]
good catch, this should likely be under test to prevent a regression.

**Comment by Alinaki** [comment]
Okay, I'll try that

**Comment by stefanpenner** [comment]
@jasonmit i don't believe a regression test was added.

**Comment by jasonmit** [comment]
@stefanpenner in the process of writing one :)

**Comment by stefanpenner** [comment]
@jasonmit :)

**Pull request merged**
