### PR TITLE
adds `interval` for >= 1.13, removing < 1.10 support

### LINKED ISSUE #27: Update as time passes?
This is to get thoughts on having the {{ago}} helper update as time passes..

I've been playing around with it but haven't got it quite there yet.. I've been doing it in HTMLBars only though - returning a stream that gets notified at the point in time that the string is expected to have changed.

Should the computed property and the helper update as time passes? For `ago`, I'm not really clear on the use cases for the computed property, if not to display in a template (which the helper covers).

- 0 to 45 seconds = 'a few seconds ago'
- 45 to 90 seconds = 'a minute ago'
- 90 seconds to 45 minutes = '2 minutes ago ... 45 minutes ago'
- 45 to 90 minutes = 'an hour ago'
- 90 minutes to 22 hours = '2 hours ago ... 22 hours ago'
- 22 to 36 hours = 'a day ago'
- 36 hours to 25 days = '2 days ago ... 25 days ago'
- 25 to 45 days = 'a month ago
- 45 to 345 days = '2 months ago ... 11 months ago'
- 345 to 547 days (1.5 years) = 'a year ago'
- 548 days+ = '2 years ago ... 20 years ago'

### PR DESCRIPTION
**Pull request by jasonmit**
Fixes #27 

This is only supported when used on >= 1.13.  I can hack support into < 1.13 but I think we should begin to deprecate supporting now 3 variations of helpers :)

### CODE REVIEW

**Comment by jasonmit** [comment]
I'll fix the failing test tonight

**Comment by jasonmit** [comment]
@stefanpenner thoughts on dropping support for Ember.Handlebars form of helpers?  We have three types of helper formats going on now:

```js
if (Ember.HTMLBars) {
    registerHelper = function(helperName, klass) {
      if (Ember.Helper && Ember.Helper.detect(klass)) {
        return registry.register(`helper:${helperName}`, klass);
      }
      return Ember.HTMLBars._registerHelper(helperName, Ember.HTMLBars.makeBoundHelper(klass));
    }
  } else {
    return registerHelper = Ember.Handlebars.helper;
  };
```

**Comment by jasonmit** [comment]
Even better if we can just support >= 1.13 and can leverage the new Ember.Helper everywhere and rely on the builtin resolver instead of registering the helpers like we do currently.

**Comment by jasonmit** [comment]
I went ahead and removed < 1.10 support.  It's too cumbersome to support three variations of helpers.

Kicking myself for going 2.0.0 now since this breaks semver.  3.0 @stefanpenner ?

**Comment by stefanpenner** [comment]
> 3.0 @stefanpenner ?

yup, this will be a 3.0

**Pull request merged**
