### PR TITLE
Adding interval to all helpers and a new 'now' helper

### PR DESCRIPTION
**Pull request by jasonmit**
`{{moment-format (now interval=1000) 'MMMM Do YYYY, h:mm:ss a'}}`

But also adds the interval option to all helpers.

### CODE REVIEW

**Comment by jasonmit** [comment]
I'm going to hold off on versioning this for now

**Comment by caalle** [comment]
@jasonmit  Any news on when this will make it into a release? Interested in the the `now` helper.

**Comment by jasonmit** [comment]
6.1.0 thanks for reminding

**Comment by caalle** [comment]
:+1: thanks for the quick action

**Pull request merged**
