### PR TITLE
Introduce `{{moment-relative}}`

### PR DESCRIPTION
**Pull request by seanpdoyle**
Using `{{moment-from-now}}` assumes the date is in the future.

Using `{{moment-to-now}}` assumes the date is in the past.

If the date is unknown (i.e. potentially in the past, potentially in the
future), use `{{moment-relative}}`.

### CODE REVIEW

**Comment by seanpdoyle** [comment]
@jasonmit unfortunately, I'm seeing test failures about the container being unable to find `helper:moment-relative`.

I've done my best to follow the pattern introduced by `moment-to-now` and `moment-from-now`, but there still seems to be an issue.

Also, due to the way the `moment-{from,to}-now` helpers are structured, I was unsure of the DRYest approach, so I just duplicated tests and logic (for now).

I've also omitted the `computed` version from the PR, although I'd gladly add it once we get to the bottom of the container lookup failure.

**Comment by stefanpenner** [comment]
:+1:

**Comment by seanpdoyle** [comment]
Also, CI isn't running.

Am I doing something wrong?

**Comment by stefanpenner** [comment]
seems like a CI bug? Unsure...

**Comment by seanpdoyle** [comment]
@stefanpenner @jasonmit force re-pushing re-ran CI.

I believe the [failure messages in CI](https://travis-ci.org/stefanpenner/ember-moment/jobs/80904934#L451-L522) are masking the more helpful / telling error message:

```
TypeError: Attempting to register an unknown factory: `helper:moment-relative`
```

**Comment by jasonmit** [comment]
> Also, due to the way the moment-{from,to}-now helpers are structured, I was unsure of the DRYest approach, so I just duplicated tests and logic (for now).

Once we remove < 1.13 support this library will get a whole lot cleaner.  It's just the awkward moment we're forced to live in right now due to two ways of declaring our helpers.

> I believe the failure messages in CI are masking the more helpful / telling error message:

I will look into it

**Comment by jasonmit** [comment]
@seanpdoyle I fixed the test issue but something is wrong with test logic since I can get all the tests to pass by making the helper just return fromNow:

```js
function(params, hash) {
    let now = moment();
    let time = moment(...params);

    if (hash.locale) {
      time = time.locale(hash.locale);
    }

    return time.fromNow(hash.hideSuffix);
  }
```

I'm not understanding either the tests or the feature itself.  I'll push the branch for you to pull down to modify.

**Comment by jasonmit** [comment]
@seanpdoyle https://github.com/stefanpenner/ember-moment/tree/moment-relative here is the branch

**Comment by seanpdoyle** [comment]
I appreciate you taking the time to help me get this working.

I don't quite understand what's going on, though. 

What are the next steps? 

Should I re-cut my branch and try again?

Why was this merged, then reverted?

> I'm not understanding either the tests or the feature itself

Could you elaborate on what you don't understand?

**Comment by jasonmit** [comment]
> Why was this merged, then reverted?

After getting the tests to run I realized something about it wasn't working as the tests described.  I didn't have enough context to try and fix it so preferred to hand it back over to you to investigate.

You can branch from or manually pull in my commit to your branch.  Ping me if you need help with anything, still happy to review.

**Comment by jasonmit** [comment]
> Could you elaborate on what you don't understand?

Pull my branch down and run the tests.  Most of the relative tests fail because the output wasn't what the assertions expect.

**Comment by seanpdoyle** [comment]
@jasonmit I was confused by the `from-now` helper (I assumed it only worked on dates in the future).

This feature isn't necessary.

**Comment by jasonmit** [comment]
No worries, we both learned something :)

**Pull request merged**
