### PR TITLE
Adding coverage for output format

### PR DESCRIPTION
**Pull request by jasonmit**
@stefanpenner

### CODE REVIEW

**Comment by jasonmit** [comment]
Tests are failing for other reasons because we need to make changes for the getOwner API.  I will tackle that in the future.

**Comment by stefanpenner** [comment]
> beta & canary

these could be added to allowed failures for now.

**Comment by jasonmit** [comment]
Okay, will add that

**Comment by jasonmit** [comment]
@stefanpenner version if you are okay with the change

**Comment by stefanpenner** [comment]
:+1:

**Pull request merged**
